### ISSUE TITLE
[1.9.4] - Crash on client start

### ISSUE THREAD

**Issue by Lazarix** [p455w0rd/p455w0rds1.9Things#1]
After updating to 1.9.4-0.0.7a, I get this crash on client start up:

https://gist.github.com/Lazarix/b65fb334935b0bf54d218cd236004c1f

Worked fine in 0.0.4a

**Comment by p455w0rd** [comment]
really weird that it's using com.google.common.collect.Iterators when I use java.util..I'll see what I can figure out

**Comment by Lazarix** [comment]
cheers!

**Comment by p455w0rd** [comment]
are you using vanilla world gen?

**Comment by Lazarix** [comment]
BoP

**Comment by p455w0rd** [comment]
can you try this and tell me your results: http://p455w0rd.net/assets/mc/p455w0rdsthings/p455w0rdsThings-1.9.4-0.0.8a.jar

**Comment by p455w0rd** [comment]
pls

**Comment by Lazarix** [comment]
Thanks for the quick fix, I can confirm this works for me too.
