### ISSUE TITLE
[1.9.4] - server side error causing client disconnect on login

### ISSUE THREAD

**Issue by Lazarix** [p455w0rd/p455w0rds1.9Things#2]
https://gist.github.com/Lazarix/5f2ed210c7c84d87f58f967b40228cc4

p455w0rdsThings-1.9.4-0.0.9a

**Comment by p455w0rd** [comment]
what forge version is the server running?

**Comment by p455w0rd** [comment]
reproduced.. InventoryPlayer#armorItemInSlot is client side only...dunno why..but it's fixed now
